// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCCnMWNT5ZjLT4Zd96r4PJO9LUa2a5SE6A',
    appId: '1:110160397297:web:216d8cb928ea92137eba50',
    messagingSenderId: '110160397297',
    projectId: 'milproject-c6cc4',
    authDomain: 'milproject-c6cc4.firebaseapp.com',
    storageBucket: 'milproject-c6cc4.firebasestorage.app',
    measurementId: 'G-BZCXL8X3M0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBns4j0t9CN3DS4g9b3cFmG-6XUCJog1AE',
    appId: '1:110160397297:android:2f24d68485f75c7c7eba50',
    messagingSenderId: '110160397297',
    projectId: 'milproject-c6cc4',
    storageBucket: 'milproject-c6cc4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCjrz_bTKbiaDCwwXeYH0vCsUNBD5DMf0w',
    appId: '1:110160397297:ios:cf2ec60d74fc26157eba50',
    messagingSenderId: '110160397297',
    projectId: 'milproject-c6cc4',
    storageBucket: 'milproject-c6cc4.firebasestorage.app',
    iosBundleId: 'com.example.mil',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCjrz_bTKbiaDCwwXeYH0vCsUNBD5DMf0w',
    appId: '1:110160397297:ios:cf2ec60d74fc26157eba50',
    messagingSenderId: '110160397297',
    projectId: 'milproject-c6cc4',
    storageBucket: 'milproject-c6cc4.firebasestorage.app',
    iosBundleId: 'com.example.mil',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCCnMWNT5ZjLT4Zd96r4PJO9LUa2a5SE6A',
    appId: '1:110160397297:web:b07032894d6647a67eba50',
    messagingSenderId: '110160397297',
    projectId: 'milproject-c6cc4',
    authDomain: 'milproject-c6cc4.firebaseapp.com',
    storageBucket: 'milproject-c6cc4.firebasestorage.app',
    measurementId: 'G-47SGJVCDF1',
  );
}
